In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))
from hsmm4acc import hsmm
from milleniumcohort import create_config

In [3]:
import pandas as pd
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import scipy

In [4]:
config = create_config('../config.yml')
config.create_data_paths()

In [5]:
import sqlite3
conn = sqlite3.connect(os.path.join(config.model_path, 'milleniumcohort.db'))

In [6]:
data_sc = pd.read_sql('''select filename, subset, state, label from data_with_states''', conn)

In [8]:
data_sc['fn_s'] = data_sc['subset'].astype('str') + data_sc['filename']

In [9]:
colname = 'label'
changepoints = (data_sc[colname].shift(1) != data_sc[colname]) | (data_sc.fn_s.shift(1) != data_sc.fn_s)
data_sc['block'] = changepoints.astype(int).cumsum()

In [15]:
grouped = data_sc.head(5000).groupby('block')

In [18]:
n_discard = 20
heads = grouped.head(n_discard)
tails = grouped.tail(n_discard)
df_filtered = df[~df.index.isin(heads.index) & ~df.index.isin(tails.index)]

                                             filename  subset  state  \
block
2     160   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      161   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      162   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      163   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      164   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      165   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      166   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      167   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      168   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      169   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      170   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      171   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      172   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      173   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      174   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      175   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      176   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      177   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      178   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      179   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      180   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      181   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      182   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      183   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      184   __022116_2015-07-09 14-13-48.bin_day2.csv       1      1
      185   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      186   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      187   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      188   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
      189   __022116_2015-07-09 14-13-48.bin_day2.csv       1      0
...                                               ...     ...    ...
11    4870  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4871  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4872  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4873  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4874  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4875  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4876  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4877  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4878  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4879  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4880  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4881  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4882  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4883  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4884  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4885  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4886  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4887  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4888  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4889  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4890  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4891  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4892  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4893  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4894  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4895  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4896  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4897  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4898  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9
      4899  __022116_2015-07-09 14-13-48.bin_day2.csv       1      9

                                                   label  \
block
2     160             Speaking, socialising face-to-face
      161             Speaking, socialising face-to-face
      162             Speaking, socialising face-to-face
      163             Speaking, socialising face-to-face
      164             Speaking, socialising face-to-face
      165             Speaking, socialising face-to-face
      166             Speaking, socialising face-to-face
      167             Speaking, socialising face-to-face
      168             Speaking, socialising face-to-face
      169             Speaking, socialising face-to-face
      170             Speaking, socialising face-to-face
      171             Speaking, socialising face-to-face
      172             Speaking, socialising face-to-face
      173             Speaking, socialising face-to-face
      174             Speaking, socialising face-to-face
      175             Speaking, socialising face-to-face
      176             Speaking, socialising face-to-face
      177             Speaking, socialising face-to-face
      178             Speaking, socialising face-to-face
      179             Speaking, socialising face-to-face
      180             Speaking, socialising face-to-face
      181             Speaking, socialising face-to-face
      182             Speaking, socialising face-to-face
      183             Speaking, socialising face-to-face
      184             Speaking, socialising face-to-face
      185             Speaking, socialising face-to-face
      186             Speaking, socialising face-to-face
      187             Speaking, socialising face-to-face
      188             Speaking, socialising face-to-face
      189             Speaking, socialising face-to-face
...                                                  ...
11    4870  Sleeping and resting (including sick in bed)
      4871  Sleeping and resting (including sick in bed)
      4872  Sleeping and resting (including sick in bed)
      4873  Sleeping and resting (including sick in bed)
      4874  Sleeping and resting (including sick in bed)
      4875  Sleeping and resting (including sick in bed)
      4876  Sleeping and resting (including sick in bed)
      4877  Sleeping and resting (including sick in bed)
      4878  Sleeping and resting (including sick in bed)
      4879  Sleeping and resting (including sick in bed)
      4880  Sleeping and resting (including sick in bed)
      4881  Sleeping and resting (including sick in bed)
      4882  Sleeping and resting (including sick in bed)
      4883  Sleeping and resting (including sick in bed)
      4884  Sleeping and resting (including sick in bed)
      4885  Sleeping and resting (including sick in bed)
      4886  Sleeping and resting (including sick in bed)
      4887  Sleeping and resting (including sick in bed)
      4888  Sleeping and resting (including sick in bed)
      4889  Sleeping and resting (including sick in bed)
      4890  Sleeping and resting (including sick in bed)
      4891  Sleeping and resting (including sick in bed)
      4892  Sleeping and resting (including sick in bed)
      4893  Sleeping and resting (including sick in bed)
      4894  Sleeping and resting (including sick in bed)
      4895  Sleeping and resting (including sick in bed)
      4896  Sleeping and resting (including sick in bed)
      4897  Sleeping and resting (including sick in bed)
      4898  Sleeping and resting (including sick in bed)
      4899  Sleeping and resting (including sick in bed)

                                                  fn_s  block
block
2     160   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      161   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      162   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      163   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      164   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      165   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      166   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      167   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      168   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      169   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      170   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      171   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      172   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      173   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      174   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      175   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      176   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      177   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      178   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      179   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      180   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      181   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      182   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      183   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      184   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      185   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      186   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      187   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      188   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
      189   1__022116_2015-07-09 14-13-48.bin_day2.csv      2
...                                                ...    ...
11    4870  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4871  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4872  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4873  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4874  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4875  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4876  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4877  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4878  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4879  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4880  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4881  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4882  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4883  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4884  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4885  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4886  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4887  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4888  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4889  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4890  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4891  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4892  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4893  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4894  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4895  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4896  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4897  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4898  1__022116_2015-07-09 14-13-48.bin_day2.csv     11
      4899  1__022116_2015-07-09 14-13-48.bin_day2.csv     11

[3180 rows x 6 columns]